### ISSUE TITLE
Does this relate to the wired version..?

### ISSUE THREAD

**Issue by amateusz** [kwakeham/DiHack#1]
Sorry for lame question, but how does your research relate to wired DI2 protocol? Is it any relevant?.. I understand that wireless DI2 creates some two networks over ANT+ PHY (one being proprietary Shimano).
(What I'm thinking instead about is fooling a lone DI2 hub into thinking it has all the peripherals on the bus it needs and will shift happily)

Nice video though. Self-aware, hacky and funny :2nd_place_medal:

**Comment by kwakeham** [comment]
Not lame. This is more related only to the Private ANT communications side only. Main focus was to reverse engineer all the settings so that new controls could be developed emulating it for controlling cycle computers only.

You're right that this doesn't have to do with the DI2 two wire interface system. I know some people and companies have done private work, but I didn't venture into it because they tend to use chipscale parts which don't have good identification marks. They also use very dense boards with advanced methods such as laser vias that are buried and blind. So the only way to interface is to wire into it with something like a decent oscilloscope and work from scratch. This is a lot harder because the system is sensitive to cable impedance I've been told. So you need to figure out how they inject data over the DC power line (probably AC coupled similar to app notes for rs-485) with inductors to prevent noise getting past the regulators. Once that's figured out you need to reverse engineer just about everything from scratch. A tall order with little payoff.
