### ISSUE TITLE
After connecting - How do you know what channel the first button press was on?

### ISSUE THREAD

**Issue by ameyer** [kwakeham/DiHack#2]
First off. THANK YOU SO MUCH. I'm trying to make my Di2 shifters control my music and my fans, and I'm basically done because of your work.

Immediately after connecting, how do you know what channel the first button press was on?

I assume I'd need a way to know the event count for each channel before anything was pressed.

Right now I set all channel counts to -1 and ignore the first button press but use it to record the event count of all of the buttons. Then on the subsequent presses I can see who incremented and know what button was pressed.

**Comment by kwakeham** [comment]
I think you're asking how does a cycle computer / reciever  know the initial condition for page 4. In some newly undocumented (eg: not in wiki yet, sorry), there is an initiation "mode". As soon as the DI2 on the bike receives an ACK to a 4f transmission type (acknowledge transmission) it transmits all the configuration pages. There are new pages that I have partially reverse engineered that tell which and where the button is, what the gears are, and a few other things. This sets the initial condition in the Garmin for the next button presses. The annoying thing is you can't use channel 3 or 4 without sending pages 0x08 and 0x09. (0x06 through 0x09 have 3 bit fields that designate supported press types, shifter type/side, and which button).  You can use CH1 and 2 as legacy DI2 bikes didn't define these pages. 

Generally the Garmin and Wahoo have been good at figuring it out even without an initiation mode because they use the first Page 4 for initial condition. The problem is this can result in first button press being ignored.

**Comment by ameyer** [comment]
Yeah - That's exactly what I was asking. 

Luckily I just have 2 buttons - But good to know I cant just add 2 more and have it magically work.

I'm using the first Page 4 for initial condition as well. I guess it doesn't really matter for me since I'll know to expect it.

Thanks!
